import { Prisma } from '@prisma/client';

export const permissions = [
  // auth
  { name: 'auth.read', module: 'auth', description: 'View own authentication details' },
  { name: 'auth.update', module: 'auth', description: 'Update own password or profile' },
  { name: 'auth.mfa.enable', module: 'auth', description: 'Enable multi-factor authentication' },
  { name: 'auth.mfa.disable', module: 'auth', description: 'Disable multi-factor authentication' },
  { name: 'auth.device.manage', module: 'auth', description: 'Manage registered devices' },
  // organization
  { name: 'organization.read', module: 'organization', description: 'View organization details' },
  {
    name: 'organization.update',
    module: 'organization',
    description: 'Edit organization settings',
  },
  {
    name: 'organization.billing.read',
    module: 'organization',
    description: 'View billing and subscription details',
  },
  {
    name: 'organization.billing.update',
    module: 'organization',
    description: 'Update billing details',
  },
  { name: 'organization.archive', module: 'organization', description: 'Archive organization' },
  // branch
  { name: 'branch.read', module: 'branch', description: 'View branches' },
  { name: 'branch.create', module: 'branch', description: 'Create new branches' },
  { name: 'branch.update', module: 'branch', description: 'Edit branch details' },
  { name: 'branch.delete', module: 'branch', description: 'Delete branches' },
  { name: 'branch.manage.users', module: 'branch', description: 'Assign users to branches' },
  // user
  { name: 'user.read', module: 'user', description: 'View users in organization' },
  { name: 'user.create', module: 'user', description: 'Create new users' },
  { name: 'user.update', module: 'user', description: 'Edit user details' },
  { name: 'user.delete', module: 'user', description: 'Delete or deactivate users' },
  { name: 'user.invite', module: 'user', description: 'Send user invitations' },
  { name: 'user.roles.assign', module: 'user', description: 'Assign roles to users' },
  { name: 'user.roles.revoke', module: 'user', description: 'Revoke roles from users' },
  // role
  { name: 'role.read', module: 'role', description: 'View roles' },
  { name: 'role.create', module: 'role', description: 'Create new roles' },
  { name: 'role.update', module: 'role', description: 'Edit roles' },
  { name: 'role.delete', module: 'role', description: 'Delete roles' },
  { name: 'role.permissions.assign', module: 'role', description: 'Assign permissions to roles' },
  { name: 'role.permissions.revoke', module: 'role', description: 'Revoke permissions from roles' },
  // product
  { name: 'product.read', module: 'product', description: 'View products' },
  { name: 'product.create', module: 'product', description: 'Create products' },
  { name: 'product.update', module: 'product', description: 'Edit products' },
  { name: 'product.delete', module: 'product', description: 'Delete products' },
  {
    name: 'product.categories.manage',
    module: 'product',
    description: 'Manage product categories',
  },
  { name: 'product.pricing.manage', module: 'product', description: 'Manage pricing rules' },
  { name: 'product.bulk.import', module: 'product', description: 'Import products in bulk' },
  { name: 'product.bulk.export', module: 'product', description: 'Export products' },
  { name: 'product.images.manage', module: 'product', description: 'Manage product images' },
  // inventory
  { name: 'inventory.read', module: 'inventory', description: 'View inventory levels' },
  { name: 'inventory.adjust', module: 'inventory', description: 'Adjust stock quantities' },
  {
    name: 'inventory.transfer',
    module: 'inventory',
    description: 'Transfer stock between branches',
  },
  { name: 'inventory.audit', module: 'inventory', description: 'View inventory audit history' },
  { name: 'inventory.alerts.view', module: 'inventory', description: 'View low stock alerts' },
  { name: 'inventory.counts.manage', module: 'inventory', description: 'Manage stock counts' },
  {
    name: 'inventory.settings.update',
    module: 'inventory',
    description: 'Update inventory settings',
  },
  // sale
  { name: 'sale.read', module: 'sale', description: 'View sales' },
  { name: 'sale.create', module: 'sale', description: 'Create sales' },
  { name: 'sale.update', module: 'sale', description: 'Edit sales before completion' },
  { name: 'sale.void', module: 'sale', description: 'Void sales' },
  { name: 'sale.refund', module: 'sale', description: 'Process refunds' },
  { name: 'sale.returns.process', module: 'sale', description: 'Process returns' },
  { name: 'sale.discounts.apply', module: 'sale', description: 'Apply discounts' },
  { name: 'sale.receipts.reprint', module: 'sale', description: 'Reprint receipts' },
  { name: 'sale.receipts.email', module: 'sale', description: 'Email receipts' },
  { name: 'sale.cancel', module: 'sale', description: 'Cancel held sales' },
  // payment
  { name: 'payment.read', module: 'payment', description: 'View payments' },
  { name: 'payment.process', module: 'payment', description: 'Process payments' },
  { name: 'payment.refund', module: 'payment', description: 'Process refunds' },
  { name: 'payment.reconcile', module: 'payment', description: 'Reconcile payments' },
  { name: 'payment.chargebacks.view', module: 'payment', description: 'View chargebacks' },
  { name: 'payment.settings.manage', module: 'payment', description: 'Manage payment settings' },
  // customer
  { name: 'customer.read', module: 'customer', description: 'View customers' },
  { name: 'customer.create', module: 'customer', description: 'Create customers' },
  { name: 'customer.update', module: 'customer', description: 'Edit customer details' },
  { name: 'customer.delete', module: 'customer', description: 'Delete customers' },
  { name: 'customer.loyalty.manage', module: 'customer', description: 'Manage loyalty programs' },
  { name: 'customer.credit.manage', module: 'customer', description: 'Manage customer credit' },
  { name: 'customer.notes.view', module: 'customer', description: 'View customer notes' },
  { name: 'customer.notes.manage', module: 'customer', description: 'Manage customer notes' },
  // supplier
  { name: 'supplier.read', module: 'supplier', description: 'View suppliers' },
  { name: 'supplier.create', module: 'supplier', description: 'Create suppliers' },
  { name: 'supplier.update', module: 'supplier', description: 'Edit suppliers' },
  { name: 'supplier.delete', module: 'supplier', description: 'Delete suppliers' },
  { name: 'supplier.contacts.manage', module: 'supplier', description: 'Manage supplier contacts' },
  {
    name: 'supplier.price-lists.view',
    module: 'supplier',
    description: 'View supplier price lists',
  },
  // report
  { name: 'report.read', module: 'report', description: 'View reports' },
  { name: 'report.sales.view', module: 'report', description: 'View sales reports' },
  { name: 'report.inventory.view', module: 'report', description: 'View inventory reports' },
  { name: 'report.financial.view', module: 'report', description: 'View financial reports' },
  { name: 'report.export', module: 'report', description: 'Export reports' },
  { name: 'report.schedule.create', module: 'report', description: 'Schedule automated reports' },
  { name: 'report.schedule.manage', module: 'report', description: 'Manage scheduled reports' },
  // settings
  { name: 'settings.general.read', module: 'settings', description: 'View general settings' },
  { name: 'settings.general.update', module: 'settings', description: 'Update general settings' },
  { name: 'settings.taxes.manage', module: 'settings', description: 'Manage tax settings' },
  {
    name: 'settings.printers.manage',
    module: 'settings',
    description: 'Manage printer configurations',
  },
  { name: 'settings.sync.manage', module: 'settings', description: 'Manage sync settings' },
  {
    name: 'settings.backups.manage',
    module: 'settings',
    description: 'Manage backup configurations',
  },
  { name: 'settings.licenses.manage', module: 'settings', description: 'Manage licenses' },
  { name: 'settings.integrations.manage', module: 'settings', description: 'Manage integrations' },
  { name: 'settings.logs.view', module: 'settings', description: 'View system logs' },
  // subscription
  { name: 'subscription.read', module: 'subscription', description: 'View subscription details' },
  { name: 'subscription.update', module: 'subscription', description: 'Update subscription' },
  { name: 'subscription.cancel', module: 'subscription', description: 'Cancel subscription' },
  { name: 'subscription.renew', module: 'subscription', description: 'Renew subscription' },
  // audit
  { name: 'audit.read', module: 'audit', description: 'View audit logs' },
  { name: 'audit.export', module: 'audit', description: 'Export audit logs' },
  { name: 'audit.config.manage', module: 'audit', description: 'Configure audit settings' },
] as Prisma.PermissionCreateManyInput[];
