export type RoleSeed = {
  name: string;
  description?: string;
  isSystem: boolean;
  permissions: string[];
};

export const systemRoles: RoleSeed[] = [
  {
    name: 'SUPER_ADMIN',
    description: 'Platform super administrator',
    isSystem: true,
    permissions: [],
  },
  {
    name: 'OWNER',
    description: 'Organization owner',
    isSystem: true,
    permissions: [
      'auth.read',
      'auth.update',
      'auth.mfa.enable',
      'auth.device.manage',
      'organization.read',
      'organization.update',
      'organization.billing.read',
      'organization.billing.update',
      'branch.read',
      'branch.create',
      'branch.update',
      'branch.delete',
      'branch.manage.users',
      'user.read',
      'user.create',
      'user.update',
      'user.delete',
      'user.invite',
      'user.roles.assign',
      'user.roles.revoke',
      'role.read',
      'role.create',
      'role.update',
      'role.delete',
      'role.permissions.assign',
      'role.permissions.revoke',
      'product.read',
      'product.create',
      'product.update',
      'product.delete',
      'product.categories.manage',
      'product.pricing.manage',
      'product.bulk.import',
      'product.bulk.export',
      'product.images.manage',
      'inventory.read',
      'inventory.adjust',
      'inventory.transfer',
      'inventory.audit',
      'inventory.alerts.view',
      'inventory.counts.manage',
      'inventory.settings.update',
      'sale.read',
      'sale.create',
      'sale.update',
      'sale.void',
      'sale.refund',
      'sale.returns.process',
      'sale.discounts.apply',
      'sale.receipts.reprint',
      'sale.receipts.email',
      'sale.cancel',
      'payment.read',
      'payment.process',
      'payment.refund',
      'payment.reconcile',
      'payment.chargebacks.view',
      'payment.settings.manage',
      'customer.read',
      'customer.create',
      'customer.update',
      'customer.delete',
      'customer.loyalty.manage',
      'customer.credit.manage',
      'customer.notes.view',
      'customer.notes.manage',
      'supplier.read',
      'supplier.create',
      'supplier.update',
      'supplier.delete',
      'supplier.contacts.manage',
      'supplier.price-lists.view',
      'report.read',
      'report.sales.view',
      'report.inventory.view',
      'report.financial.view',
      'report.export',
      'report.schedule.create',
      'report.schedule.manage',
      'settings.general.read',
      'settings.general.update',
      'settings.taxes.manage',
      'settings.printers.manage',
      'settings.sync.manage',
      'settings.backups.manage',
      'settings.licenses.manage',
      'settings.integrations.manage',
      'settings.logs.view',
      'subscription.read',
      'subscription.update',
      'subscription.cancel',
      'subscription.renew',
      'audit.read',
      'audit.export',
      'audit.config.manage',
    ],
  },
  {
    name: 'MANAGER',
    description: 'Business manager',
    isSystem: true,
    permissions: [
      'auth.read',
      'auth.update',
      'organization.read',
      'organization.update',
      'branch.read',
      'branch.update',
      'user.read',
      'user.invite',
      'product.read',
      'product.create',
      'product.update',
      'inventory.read',
      'inventory.adjust',
      'inventory.audit',
      'inventory.alerts.view',
      'sale.read',
      'sale.create',
      'sale.update',
      'sale.refund',
      'sale.returns.process',
      'sale.discounts.apply',
      'sale.receipts.reprint',
      'sale.receipts.email',
      'sale.cancel',
      'payment.read',
      'payment.process',
      'payment.reconcile',
      'customer.read',
      'customer.create',
      'customer.update',
      'supplier.read',
      'supplier.create',
      'supplier.update',
      'report.read',
      'report.sales.view',
      'report.inventory.view',
      'report.financial.view',
      'report.export',
      'settings.general.read',
      'settings.printers.manage',
      'settings.sync.manage',
      'audit.read',
    ],
  },
  {
    name: 'SUPERVISOR',
    description: 'Shift supervisor',
    isSystem: true,
    permissions: [
      'auth.read',
      'product.read',
      'product.create',
      'product.update',
      'inventory.read',
      'inventory.adjust',
      'sale.read',
      'sale.create',
      'sale.update',
      'sale.refund',
      'sale.returns.process',
      'sale.discounts.apply',
      'sale.receipts.reprint',
      'sale.receipts.email',
      'customer.read',
      'customer.create',
      'customer.update',
      'report.read',
      'report.sales.view',
      'report.export',
    ],
  },
  {
    name: 'CASHIER',
    description: 'Frontline cashier',
    isSystem: true,
    permissions: [
      'auth.read',
      'product.read',
      'sale.create',
      'sale.cancel',
      'sale.receipts.print',
      'sale.receipts.email',
      'customer.read',
      'customer.create',
      'payment.process',
      'report.read',
    ],
  },
  {
    name: 'INVENTORY_MANAGER',
    description: 'Inventory manager',
    isSystem: true,
    permissions: [
      'auth.read',
      'product.read',
      'inventory.read',
      'inventory.adjust',
      'inventory.transfer',
      'inventory.audit',
      'inventory.alerts.view',
      'inventory.counts.manage',
      'purchase.read',
      'purchase.create',
      'purchase.receive',
      'supplier.read',
      'report.inventory.view',
    ],
  },
  {
    name: 'ACCOUNTANT',
    description: 'Finance and reporting',
    isSystem: true,
    permissions: [
      'auth.read',
      'sale.read',
      'payment.read',
      'payment.reconcile',
      'report.sales.view',
      'report.financial.view',
      'report.export',
      'customer.credit.manage',
      'audit.read',
    ],
  },
  {
    name: 'REPORT_VIEWER',
    description: 'Read-only reporting',
    isSystem: true,
    permissions: [
      'auth.read',
      'report.read',
      'report.sales.view',
      'report.inventory.view',
      'report.financial.view',
      'report.export',
    ],
  },
] as const;
