export const Permissions = {
  AUTH_LOGIN: 'AUTH.LOGIN',
  AUTH_LOGOUT: 'AUTH.LOGOUT',
  AUTH_REGISTER: 'AUTH.REGISTER',
  USER_READ: 'USER.READ',
  USER_CREATE: 'USER.CREATE',
  USER_UPDATE: 'USER.UPDATE',
  CUSTOMER_VIEW: 'CUSTOMER.VIEW',
  CUSTOMER_CREATE: 'CUSTOMER.CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER.UPDATE',
  SALE_CREATE: 'SALE.CREATE',
  SALE_VIEW: 'SALE.VIEW',
  SALE_VOID: 'SALE.VOID',
  PAYMENT_CREATE: 'PAYMENT.CREATE',
  RECEIPT_PRINT: 'RECEIPT.PRINT',
  INVENTORY_READ: 'INVENTORY.READ',
  INVENTORY_ADJUST: 'INVENTORY.ADJUST',
  INVENTORY_TRANSFER: 'INVENTORY.TRANSFER',
} as const;

export const MovementTypes = {
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  RETURN: 'RETURN',
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  ADJUSTMENT: 'ADJUSTMENT',
  DAMAGE: 'DAMAGE',
  EXPIRED: 'EXPIRED',
} as const;

export const PaymentMethods = {
  CASH: 'CASH',
  MPESA: 'MPESA',
  CARD: 'CARD',
  BANK: 'BANK',
  CREDIT: 'CREDIT',
} as const;

export const PaymentStatuses = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export const SaleStatuses = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  VOIDED: 'VOIDED',
  REFUNDED: 'REFUNDED',
} as const;

export const NumberSequenceTypes = {
  SALE: 'SALE',
  PURCHASE: 'PURCHASE',
  TRANSFER: 'TRANSFER',
  RETURN: 'RETURN',
  ADJUSTMENT: 'ADJUSTMENT',
  RECEIPT: 'RECEIPT',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  GOODS_RECEIPT: 'GOODS_RECEIPT',
} as const;
